import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import type { DraftMode } from "@wcf/shared";

interface CreateLeagueBody {
  name: string;
  draft_mode: DraftMode;
  pick_time_limit_seconds?: number;
  slow_draft_hours?: number;
  max_participants?: number;
}

export async function POST(request: NextRequest) {
  const supabase = createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  let body: CreateLeagueBody;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const { name, draft_mode, pick_time_limit_seconds, slow_draft_hours, max_participants } =
    body;

  // Validation
  if (!name || typeof name !== "string" || name.trim().length < 3) {
    return NextResponse.json(
      { error: "League name must be at least 3 characters." },
      { status: 400 }
    );
  }

  if (!["live", "slow"].includes(draft_mode)) {
    return NextResponse.json(
      { error: "draft_mode must be 'live' or 'slow'." },
      { status: 400 }
    );
  }

  const validPickTimes = [30, 60, 90, 120];
  const pickTime =
    draft_mode === "live"
      ? (pick_time_limit_seconds ?? 60)
      : 60;
  if (draft_mode === "live" && !validPickTimes.includes(pickTime)) {
    return NextResponse.json(
      { error: "pick_time_limit_seconds must be 30, 60, 90, or 120." },
      { status: 400 }
    );
  }

  const validSlowHours = [12, 24, 48];
  const slowHours =
    draft_mode === "slow"
      ? (slow_draft_hours ?? 24)
      : 24;
  if (draft_mode === "slow" && !validSlowHours.includes(slowHours)) {
    return NextResponse.json(
      { error: "slow_draft_hours must be 12, 24, or 48." },
      { status: 400 }
    );
  }

  const maxPart = max_participants ?? 8;
  if (maxPart < 2 || maxPart > 20) {
    return NextResponse.json(
      { error: "max_participants must be between 2 and 20." },
      { status: 400 }
    );
  }

  // Get commissioner's display name
  const { data: profile } = await supabase
    .from("profiles")
    .select("username")
    .eq("id", user.id)
    .single();

  const displayName =
    profile?.username ?? user.email?.split("@")[0] ?? "Commissioner";

  // Insert league (invite_code generated by DB default)
  const { data: league, error: leagueError } = await supabase
    .from("leagues")
    .insert({
      name: name.trim(),
      commissioner_id: user.id,
      draft_mode,
      draft_status: "pending",
      draft_order: [],
      current_pick_index: 0,
      pick_time_limit_seconds: pickTime,
      slow_draft_hours: slowHours,
      current_pick_deadline: null,
      max_participants: maxPart,
    })
    .select()
    .single();

  if (leagueError || !league) {
    console.error("League insert error:", leagueError?.message);
    return NextResponse.json(
      { error: leagueError?.message ?? "Failed to create league." },
      { status: 500 }
    );
  }

  // Add commissioner as first member
  const { error: memberError } = await supabase.from("league_members").insert({
    league_id: league.id,
    user_id: user.id,
    display_name: displayName,
    total_points: 0,
    goals_scored: 0,
    assists: 0,
    bonus_points: 0,
    free_transfers: 0,
  });

  if (memberError) {
    console.error("League member insert error:", memberError.message);
  }

  // Seed the first transfer window — opens 3 days from now, lasts 24 hours.
  // The update-transfer-windows edge function will auto-chain subsequent windows.
  const firstOpen = new Date();
  firstOpen.setDate(firstOpen.getDate() + 3);
  const firstClose = new Date(firstOpen);
  firstClose.setHours(firstClose.getHours() + 24);

  const { error: windowError } = await supabase.from("transfer_windows").insert({
    league_id: league.id,
    opens_at: firstOpen.toISOString(),
    closes_at: firstClose.toISOString(),
  });

  if (windowError) {
    console.error("Transfer window seed error:", windowError.message);
  }

  return NextResponse.json(
    { league_id: league.id, invite_code: league.invite_code },
    { status: 201 }
  );
}
